# Generated by Django 5.1.4 on 2025-01-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_taskmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
