services:
  flask-app:
    build:
      context: .
    container_name: agent-system
    ports:
      - "5000:5000"
    depends_on:
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A service.celery.celery worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
